### ISSUE TITLE
Disable cache option

### ISSUE THREAD

**Issue by nicksavov** [OSTraining/OSTimer#7]
Disable cache option:
https://www.alledia.com/forum/ostimer/55/#275

See mod_custom for how it does it.

**Comment by htmgarcia** [comment]
Based on a quick test I did, we only need to add a param named cache in the module. Automatically this will be taken by Joomla.

Whithout cache param:

1. I have an OSTimer module enabled
2. Enabled cache from System > Global configuration > System > Cache: on - conservating cache
3. Visited my test site in frontend to generate some cached content.
4. Checked the current cached elements from System > Clear cache. mod_timer wasn't listed

Whith cache param:

I added cache param in mod_ostimer.xml (currently I don't have permissions to do commits to the repository, so I'm posting the code here)

```
<fieldset name="advanced">
                <field
                        name="cache"
                        type="list"
                        default="1"
                        label="COM_MODULES_FIELD_CACHING_LABEL"
                        description="COM_MODULES_FIELD_CACHING_DESC">
                    <option
                            value="1">JGLOBAL_USE_GLOBAL</option>
                    <option
                            value="0">COM_MODULES_FIELD_VALUE_NOCACHING</option>
                </field>
            </fieldset>
```

1. Go to Extensions > Module manager > My OSTimer module. I just save the module without changing anything; this, is order to have the cache param added in database.
2. Visited my test site in frontend to generate some cached content.
3. Checked the current cached elements from System > Clear cache. mod_timer is listed this time

If I edit the module again to disable the cache (no caching), refresh the site and check again System > Clear cache. mod_timer is not listed.

Note: in the steps that mention "Visited my test site", is possible you need to clear cache first to see the same result.

**Comment by nicksavov** [comment]
Nice work, Valentin!

I'm not sure why commit access wasn't working for you, but I tried resetting it. Could you give it a try now?

**Comment by htmgarcia** [comment]
Thanks @nicksavov !
@billtomczak gave me permissions to do commits.
Here we go: https://github.com/OSTraining/OSTimer/commit/b70e8f24392c8580b162d80876686fc6eacfee1e

**Comment by htmgarcia** [comment]
Merged into master https://github.com/OSTraining/OSTimer/commit/c401b3ed3394f4444d98229bf4e5dfa8d1b8e8bf

**Comment by andergmartins** [comment]
Cool! :) Nice job @htmgarcia

**Comment by htmgarcia** [comment]
Thanks! :)
